/**
 * Report rendering.
 *
 * The report is Markdown because a human decides whether to trust it, and the
 * things that make it trustworthy -- which platform saw what, at which commit,
 * and which rows are unproven rather than passing -- are on its face rather
 * than in an appendix.
 */

import type { PlatformEvidence } from './evidence.ts';
import { totalPassed, totalSkipped, totalTests } from './evidence.ts';
import type { GateReport } from './gate.ts';

export interface RenderInput {
  readonly gate: GateReport;
  readonly platforms: readonly PlatformEvidence[];
  readonly generatedAt: string;
  readonly commit: string;
  readonly generator: string;
}

const SYMBOL: Record<string, string> = { pass: 'PASS', fail: 'FAIL', unproven: 'UNPROVEN' };

export function renderReport(input: RenderInput): string {
  const { gate } = input;
  const lines: string[] = [];

  lines.push(`# Stage ${String(gate.stage)} qualification report`);
  lines.push('');
  lines.push(
    `> Harness-generated by \`${input.generator}\`. This is the artifact the build guide` +
      ' names as the only one permitted to claim a gate passed. It is generated from',
  );
  lines.push(
    '> measurements, never from the plan or the decision log, so it can disagree with them.',
  );
  lines.push('');
  lines.push(`**Verdict: ${gate.verdict}** — ${gate.summary}`);
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('| --- | --- |');
  lines.push(`| Stage | ${String(gate.stage)} |`);
  lines.push(`| Commit | \`${input.commit}\` |`);
  lines.push(`| Generated at | ${input.generatedAt} |`);
  lines.push(
    `| Platforms in evidence | ${
      input.platforms.length === 0
        ? '**none**'
        : input.platforms.map((p) => `\`${p.platform}\``).join(', ')
    } |`,
  );
  lines.push('');

  lines.push('## Exit gate');
  lines.push('');
  lines.push('| Row | Requirement | Status | Evidence |');
  lines.push('| --- | --- | --- | --- |');
  for (const entry of gate.rows) {
    lines.push(
      `| ${entry.id} | ${entry.requirement} | **${SYMBOL[entry.status] ?? entry.status}** | ${entry.evidence} |`,
    );
  }
  lines.push('');

  if (gate.verdict !== 'PASS') {
    lines.push('### Why this is not a pass');
    lines.push('');
    for (const entry of gate.rows.filter((r) => r.status !== 'pass')) {
      lines.push(`- **${entry.id}** (${entry.status}): ${entry.evidence}`);
    }
    lines.push('');
    lines.push(
      'A row is `unproven` when the observation required to decide it was never made.' +
        ' That is deliberately not the same as `fail`, and neither is a pass.',
    );
    lines.push('');
  }

  lines.push('## Platform evidence');
  lines.push('');
  if (input.platforms.length === 0) {
    lines.push('**No platform records were supplied.** Nothing above rests on a measurement.');
    lines.push('');
  } else {
    for (const platform of input.platforms) {
      lines.push(`### \`${platform.platform}\``);
      lines.push('');
      lines.push('| Field | Value |');
      lines.push('| --- | --- |');
      lines.push(`| Node | ${platform.nodeVersion} |`);
      lines.push(`| Commit | \`${platform.commit}\` |`);
      lines.push(`| Collected at | ${platform.collectedAt} |`);
      lines.push(`| Run | ${platform.runUrl ?? '_local_'} |`);
      lines.push(
        `| Tests | ${String(totalPassed(platform))} passed of ${String(totalTests(platform))}` +
          `${totalSkipped(platform) > 0 ? `, ${String(totalSkipped(platform))} skipped` : ''} |`,
      );
      lines.push(`| Empty-snapshot digest | \`${platform.digests.emptySnapshot}\` |`);
      lines.push(`| Asset-tree digest | \`${platform.digests.assetTreeWithNestedFiles}\` |`);
      lines.push('');
      lines.push('| Suite | Files | Tests | Passed | Skipped | Failed |');
      lines.push('| --- | --- | --- | --- | --- | --- |');
      for (const suite of platform.suites) {
        lines.push(
          `| ${suite.project} | ${String(suite.files)} | ${String(suite.tests)} | ` +
            `${String(suite.passed)} | ${String(suite.skipped)} | ${String(suite.failed.length)} |`,
        );
      }
      lines.push('');

      const failures = platform.suites.flatMap((suite) => suite.failed);
      // Reasons are keyed by name so a record collected before the reason field
      // existed still renders -- as names alone, which is what it holds.
      const reasons = new Map(
        platform.suites.flatMap((suite) =>
          (suite.failures ?? []).map((failure) => [failure.name, failure.reason] as const),
        ),
      );
      if (failures.length > 0) {
        // A record with failures does not satisfy a platform requirement, so the
        // report must say what failed rather than only that something did -- and
        // why, because "assertion" and "timeout" are different defects with
        // different fixes and the log that once distinguished them has expired.
        lines.push(`**Failing tests on \`${platform.platform}\`:**`);
        lines.push('');
        for (const name of failures) {
          const reason = reasons.get(name);
          lines.push(reason === undefined ? `- \`${name}\`` : `- \`${name}\` — ${reason}`);
        }
        lines.push('');
      }
    }
  }

  return `${lines.join('\n')}\n`;
}
